name: bmi_calculator
description: A BMI Calculator App with Firebase Authentication

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  # UI Components
  syncfusion_flutter_gauges: ^20.4.48  # Updated to compatible version

  # Optional Firebase UI (if needed)
  # firebase_ui_auth: ^1.2.0  # Uncomment if using Firebase UI

  # Form validation
  flutter_form_builder: ^9.0.0  # Optional for enhanced forms
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  provider: ^6.1.4
  firebase_ui_auth: ^1.16.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  localization:
    arb-dir: lib/l10n/
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart

